templates:
  run_docker_build: run_docker_build_matrix.tmpl

channels:
  sources:
  - conda-forge
  target: conda-forge
appveyor:
  secure:
    BINSTAR_TOKEN: fLfuo8cpK0MHhcqTNadUVNIMzHPkSYLMJOfYqQwcDSehCQHd5ITy8KkWRQC52vF7
travis:
  secure:
    BINSTAR_TOKEN: Ex7c/bXpuYw2dT2rC8+yo4MGuNwKbdcNPUrtGls04D66JlhOGm1RU/oiqumOeqLp2nEPcOeExnS1PnFoXfk+1iJHLbQyCzUBMZJezoMvksAPGfz1f9Rc/t+QD2gyuWRahUxdOZ9jStEWOGAJaJl5iEV1n5ITzGLLmcmvZmdBhh8=
