templates:
  run_docker_build: run_docker_build_matrix.tmpl

channels:
  sources:
  - conda-forge
  target: conda-forge
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
travis:
  secure:
    BINSTAR_TOKEN: Uh+3Xas8eeE4zWvsGUZdZyettGfbXJ9GFAqETG5AGGYOhDEdXz4u/YGX8Lzxr5WvTcMiWGsIVI7mpwokTXEZ7Z5itCF7TQ2O4JVNt7sRjeqNw/bhSpQH9+hNXKQgV8PVvCIx9WCoDY9ejbtY5/v75sZEBdpOijZ3WdHmfrzeMUg=
