appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
travis:
  secure:
    BINSTAR_TOKEN: NblryNZfknUyRvl/U7vTBbaI+hdgcRPCpNyjIvP9UUprN8kPHdAaXOWDbb6pbnZmTTfGHoaFrzwF5mlBYfGXG7Vq3FjLOtqOPtNELQ8mWaW6qhyvKUBY7Qtkw4nQw1ZkhLgU/n0gFItN0ALIuVVZqNTQp0Zn7pbzO+R5b6MuO8o=
